services:
  api:
    environment:
      LOG_LEVEL: debug
    volumes:
      - ./deployments/api/src:/app/deployments/api/src
      - ./packages:/app/packages
    command:
      - uvicorn
      - stitch.api.main:app
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
      - --reload
      - --reload-dir
      - /app/deployments/api/src
      - --reload-dir
      - /app/packages
      - --reload-exclude
      - "*/tests/*"
