services:
  api:
    environment:
      LOG_LEVEL: debug
    volumes:
      - ./deployments/api/src:/app/deployments/api/src
      - ./packages/stitch-core/src:/app/packages/stitch-core/src
    develop:
      watch:
        - path: ./uv.lock
          action: rebuild
        - path: ./deployments/api/pyproject.toml
          action: rebuild

    command:
      ["uvicorn", "stitch.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
