-- Generated by init_db.py
-- DDL for stitch-api models (uses SQLAlchemy ORM introspection)

CREATE TYPE membershipstatus AS ENUM ('ACTIVE', 'INACTIVE', 'INVALID');

CREATE TABLE cc_reservoirs_sources (
	name VARCHAR NOT NULL, 
	basin VARCHAR NOT NULL, 
	depth FLOAT NOT NULL, 
	geofence JSONB NOT NULL, 
	id BIGSERIAL NOT NULL, 
	PRIMARY KEY (id)
);

CREATE TABLE gem_sources (
	name VARCHAR NOT NULL, 
	country VARCHAR NOT NULL, 
	lat FLOAT NOT NULL CHECK (lat >= -90 AND lat <= 90), 
	lon FLOAT NOT NULL CHECK (lon >= -180 AND lon <= 180), 
	id BIGSERIAL NOT NULL, 
	PRIMARY KEY (id)
);

CREATE TABLE rmi_manual_sources (
	name_override VARCHAR, 
	gwp FLOAT, 
	gor FLOAT CHECK (gor >= 0 AND gor <= 1), 
	country VARCHAR, 
	latitude FLOAT CHECK (latitude >= -90 AND latitude <= 90), 
	longitude FLOAT CHECK (longitude >= -180 AND longitude <= 180), 
	id BIGSERIAL NOT NULL, 
	PRIMARY KEY (id)
);

CREATE TABLE users (
	id SERIAL NOT NULL, 
	first_name VARCHAR NOT NULL, 
	last_name VARCHAR NOT NULL, 
	email VARCHAR NOT NULL, 
	PRIMARY KEY (id)
);

CREATE TABLE wm_sources (
	field_name VARCHAR NOT NULL, 
	field_country VARCHAR NOT NULL, 
	production FLOAT NOT NULL, 
	id BIGSERIAL NOT NULL, 
	PRIMARY KEY (id)
);

CREATE TABLE resources (
	id BIGSERIAL NOT NULL, 
	repointed_id BIGINT, 
	name VARCHAR, 
	country VARCHAR(3), 
	created TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	created_by_id INTEGER NOT NULL, 
	last_updated_by_id INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(repointed_id) REFERENCES resources (id), 
	FOREIGN KEY(created_by_id) REFERENCES users (id), 
	FOREIGN KEY(last_updated_by_id) REFERENCES users (id)
);

CREATE INDEX rp_repointed_id_idx ON resources (repointed_id);

CREATE TABLE memberships (
	id SERIAL NOT NULL, 
	resource_id BIGINT NOT NULL, 
	source VARCHAR(10) NOT NULL, 
	source_pk BIGINT NOT NULL, 
	status membershipstatus NOT NULL, 
	created TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	created_by_id INTEGER NOT NULL, 
	last_updated_by_id INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uc_source_source_pk UNIQUE (resource_id, source, source_pk), 
	FOREIGN KEY(resource_id) REFERENCES resources (id), 
	FOREIGN KEY(created_by_id) REFERENCES users (id), 
	FOREIGN KEY(last_updated_by_id) REFERENCES users (id)
);

-- Seed data (generated from ORM model instances)

INSERT INTO users (id, first_name, last_name, email) VALUES (1, 'Seed', 'User', 'seed@example.com');

INSERT INTO gem_sources (name, country, lat, lon, id) VALUES ('Permian Basin Field', 'USA', 31.8, -102.3, 1);

INSERT INTO gem_sources (name, country, lat, lon, id) VALUES ('North Sea Platform', 'GBR', 57.5, 1.5, 2);

INSERT INTO wm_sources (field_name, field_country, production, id) VALUES ('Eagle Ford Shale', 'USA', 125000.5, 1);

INSERT INTO wm_sources (field_name, field_country, production, id) VALUES ('Ghawar Field', 'SAU', 500000.0, 2);

INSERT INTO rmi_manual_sources (name_override, gwp, gor, country, latitude, longitude, id) VALUES ('Custom Override Name', 25.5, 0.45, 'CAN', 56.7, -111.4, 1);

INSERT INTO cc_reservoirs_sources (name, basin, depth, geofence, id) VALUES ('Alberta Deep Basin', 'Western Canadian Sedimentary', 3500.0, '[[56.0, -115.0], [56.0, -110.0], [54.0, -110.0], [54.0, -115.0]]'::jsonb, 1);

INSERT INTO resources (id, repointed_id, name, country, created_by_id, last_updated_by_id) VALUES (1, NULL, 'Multi-Source Asset', 'USA', 1, 1);

INSERT INTO resources (id, repointed_id, name, country, created_by_id, last_updated_by_id) VALUES (2, NULL, 'Single Source Asset', 'GBR', 1, 1);

INSERT INTO memberships (id, resource_id, source, source_pk, status, created_by_id, last_updated_by_id) VALUES (1, 1, 'gem', 1, 'ACTIVE', 1, 1);

INSERT INTO memberships (id, resource_id, source, source_pk, status, created_by_id, last_updated_by_id) VALUES (2, 1, 'wm', 1, 'ACTIVE', 1, 1);

INSERT INTO memberships (id, resource_id, source, source_pk, status, created_by_id, last_updated_by_id) VALUES (3, 1, 'rmi', 1, 'ACTIVE', 1, 1);

INSERT INTO memberships (id, resource_id, source, source_pk, status, created_by_id, last_updated_by_id) VALUES (4, 2, 'gem', 2, 'ACTIVE', 1, 1);

-- Reset sequences after explicit ID inserts

SELECT setval('users_id_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM users), false);

SELECT setval('gem_sources_id_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM gem_sources), false);

SELECT setval('wm_sources_id_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM wm_sources), false);

SELECT setval('rmi_manual_sources_id_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM rmi_manual_sources), false);

SELECT setval('cc_reservoirs_sources_id_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM cc_reservoirs_sources), false);

SELECT setval('resources_id_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM resources), false);

SELECT setval('memberships_id_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM memberships), false);

