name: Docker build & test

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_docker_image:
    name: "Call build and push action"
    uses: ./.github/workflows/build-and-push-Docker-image.yml
    secrets: inherit
    permissions:
      packages: write
      contents: read
    with:
      dockerfile: deployments/api/Dockerfile
      image-name: ${{ github.event.repository.name }}-api
      image-tag: ${{
          github.event_name == 'pull_request' && format('{0}{1}','pr', github.event.pull_request.number) ||
          github.event_name == 'schedule' && 'nightly' ||
          github.event_name == 'push' && github.ref_name ||
          github.event_name == 'workflow_dispatch' && github.ref_name ||
          github.sha
        }}

  deploy-db:
    name: "Create DB"
    uses: ./.github/workflows/deploy-db.yml
    secrets: inherit

  run-db-init:
    name: "Run DB init"
    uses: ./.github/workflows/run-db-init.yml
    secrets: inherit
    needs: [build_docker_image, deploy-db]
    with:
      full-image-name: ${{ needs.build_docker_image.outputs.digest-image-name }}
      postgres-host: ${{ needs.deploy-db.outputs.postgres-host }}
      postgres-port: ${{ needs.deploy-db.outputs.postgres-port }}
      postgres-db: ${{ needs.deploy-db.outputs.postgres-db }}

  deploy-docker:
    name: "Deploy"
    uses: ./.github/workflows/deploy-api.yml
    secrets: inherit
    needs: [build_docker_image, deploy-db, run-db-init]
    with:
      full-image-name: ${{ needs.build_docker_image.outputs.digest-image-name }}
      containerAppName: ${{
          github.event_name == 'pull_request' && format('{0}{1}','pr', github.event.pull_request.number) ||
          github.event_name == 'schedule' && 'nightly' ||
          github.event_name == 'push' && github.ref_name ||
          github.event_name == 'workflow_dispatch' && github.ref_name ||
          github.sha
        }}-api
      postgres-host: ${{ needs.deploy-db.outputs.postgres-host }}
      postgres-port: ${{ needs.deploy-db.outputs.postgres-port }}
      postgres-db: ${{ needs.deploy-db.outputs.postgres-db }}
      postgres-user: ${{ needs.deploy-db.outputs.postgres-user }}

  add-comment:
    if: ${{ github.event_name == 'pull_request' }}
    uses: RMI-PACTA/actions/.github/workflows/add-comment-table.yml@main
    needs: [build_docker_image]
    with:
      header: "Docker build status"
