on:
  workflow_call:

jobs:
  build:
    name: "docker compose build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up example Env file
        run: cp .env.example .env

      - run: docker compose build
