---
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: Node Package Checks
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}-${{ github.event_action }}
  cancel-in-progress: true

jobs:
  test:
    name: "Tests"
    uses: ./.github/workflows/node-test.yml

  lint:
    name: "Linting"
    uses: ./.github/workflows/node-lint.yml

  build:
    name: "Build"
    uses: ./.github/workflows/node-build.yml
